# Generated by Django 5.2.3 on 2025-07-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labels',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
