# Generated by Django 5.2.3 on 2025-06-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
