# Generated by Django 5.2.3 on 2025-07-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_executor_alter_tasks_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
