# Generated by Django 5.2.3 on 2025-07-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_rename_create_at_labels_created_at'),
        ('tasks', '0008_alter_tasks_author_alter_tasks_executor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='label',
        ),
        migrations.AddField(
            model_name='tasks',
            name='label',
            field=models.ManyToManyField(null=True, related_name='tasks', to='labels.labels'),
        ),
    ]
