# Generated by Django 5.2.3 on 2025-07-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_rename_create_at_labels_created_at'),
        ('tasks', '0009_remove_tasks_label_tasks_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='label',
            field=models.ManyToManyField(null=True, related_name='labels', to='labels.labels'),
        ),
    ]
